# Generated by Django 5.0 on 2024-04-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workerModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=150)),
                ('apm', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('edad', models.CharField(max_length=5)),
                ('matricula', models.CharField(max_length=20)),
                ('adscripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('n_afil', models.CharField(max_length=11)),
                ('calle', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('mcpio', models.CharField(max_length=150)),
                ('tel_t', models.CharField(max_length=10)),
                ('tel_p', models.CharField(max_length=10)),
                ('tel_c', models.CharField(max_length=10)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='regH',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=100)),
                ('apm', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('f_nac', models.CharField(max_length=50)),
                ('edad', models.FloatField()),
                ('alergias', models.CharField(max_length=150)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('regp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.workermodel')),
            ],
            options={
                'db_table': 'registerH',
            },
        ),
        migrations.CreateModel(
            name='authPer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=100)),
                ('apm', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=30)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('authPer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.workermodel')),
            ],
            options={
                'db_table': 'authPer',
            },
        ),
    ]
