# Generated by Django 5.0 on 2024-05-11 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_workermodel_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='entRec',
            field=models.CharField(default=None, max_length=180),
        ),
        migrations.AlterField(
            model_name='regh',
            name='f_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 11, 14, 12, 22, 890869), null=True),
        ),
    ]
