# Generated by Django 5.0 on 2024-05-11 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_workermodel_entrec_alter_regh_f_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 11, 14, 14, 28, 709231), null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='entRec',
            field=models.CharField(default='CMNO', max_length=180),
        ),
    ]
