# Generated by Django 5.0 on 2024-05-11 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_workermodel_createdat_alter_workermodel_entrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 11, 15, 6, 19, 975634), null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='entRec',
            field=models.CharField(default=None, max_length=180),
        ),
    ]
