# Generated by Django 5.0 on 2024-05-11 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_alter_workermodel_createdat_alter_workermodel_entrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 11, 15, 19, 31, 687254), null=True),
        ),
    ]
