# Generated by Django 5.0 on 2024-05-12 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_alter_workermodel_createdat_alter_workermodel_entrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 12, 10, 21, 57, 185065), null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='entRec',
            field=models.CharField(blank=True, default='CMNO', max_length=180),
        ),
    ]
