# Generated by Django 5.0 on 2024-05-12 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_alter_workermodel_createdat_alter_workermodel_entrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 12, 11, 34, 15, 346981), null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='entRec',
            field=models.CharField(max_length=100),
        ),
    ]
