# Generated by Django 5.0 on 2024-05-15 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_alter_workermodel_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 15, 13, 7, 52, 543200), null=True),
        ),
    ]
