# Generated by Django 5.0 on 2024-05-24 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_rename_regp_id_regh_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 24, 11, 4, 20, 412013), null=True),
        ),
    ]
