# Generated by Django 5.0 on 2024-05-27 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_alter_workermodel_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 27, 23, 42, 40, 890083), null=True),
        ),
    ]
